// <auto-generated />
using System;
using CoreReport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreReport.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreReport.Models.Reporting", b =>
                {
                    b.Property<string>("SlNo")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("FirstLevel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsEventLog")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MultipleReport")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Para1")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Para2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Para3")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Para4")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("QryType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Qryname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ReportLevel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ReportName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ReportPath")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("SecondLevel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ThirdLevel")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("xmlTableName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SlNo");

                    b.ToTable("Reportings");
                });
#pragma warning restore 612, 618
        }
    }
}
